# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modules.LineEditMainDir import LineEditMainDir
from modules.TreeFiles import TreeFiles
import widgets.RCC_Resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_main_dir = LineEditMainDir(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(14)
        self.le_main_dir.setFont(font)
        self.le_main_dir.setAlignment(QtCore.Qt.AlignCenter)
        self.le_main_dir.setReadOnly(True)
        self.le_main_dir.setObjectName("le_main_dir")
        self.gridLayout.addWidget(self.le_main_dir, 0, 0, 1, 1)
        self.tree_files = TreeFiles(self.centralwidget)
        self.tree_files.setDragEnabled(True)
        self.tree_files.setDragDropOverwriteMode(True)
        self.tree_files.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tree_files.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tree_files.setAlternatingRowColors(True)
        self.tree_files.setColumnCount(1)
        self.tree_files.setObjectName("tree_files")
        self.gridLayout.addWidget(self.tree_files, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_gen = QtWidgets.QPushButton(self.centralwidget)
        self.pb_gen.setObjectName("pb_gen")
        self.horizontalLayout.addWidget(self.pb_gen)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extractify"))
        self.le_main_dir.setPlaceholderText(_translate("MainWindow", "Choose main directory..."))
        self.pb_gen.setText(_translate("MainWindow", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
